repository:
  name: rei_seattle
  description: "Seattle Homes - AI-powered real estate investment platform for the Greater Seattle area"
  homepage: https://seattlehomes.com
  topics:
    - real-estate
    - investment-analysis
    - seattle
    - roi-calculator
    - nextjs
    - typescript
    - tailwindcss
    - ai-powered
    - property-analysis
    - responsive-design
    - nwmls
    - investment-metrics
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: false 